Repository GSG-G13/eCommerse-NYS, pull requests merged in 2023-03, with the labels that each got.

#3 2-add-file-user
  user/CSS/user.css
  user/user.html
  user/user.js
Labels: good first issue

#5 add Admin files
  Admin/CSS/admin.css
  Admin/admin.html
  Admin/admin.js
  Admin/webfonts/fa-brands-400.ttf
  Admin/webfonts/fa-brands-400.woff2
  Admin/webfonts/fa-regular-400.ttf
  Admin/webfonts/fa-regular-400.woff2
  Admin/webfonts/fa-solid-900.ttf
  Admin/webfonts/fa-solid-900.woff2
  Admin/webfonts/fa-v4compatibility.ttf
  Admin/webfonts/fa-v4compatibility.woff2
Labels: documentation

#6 Add Folder LOGIN and USER
  login/login.css
  login/login.html
  login/login.js
  login/webfonts/fa-brands-400.ttf
  login/webfonts/fa-brands-400.woff2
  login/webfonts/fa-regular-400.ttf
  login/webfonts/fa-regular-400.woff2
  login/webfonts/fa-solid-900.ttf
  login/webfonts/fa-solid-900.woff2
  login/webfonts/fa-v4compatibility.ttf
  login/webfonts/fa-v4compatibility.woff2
  user/CSS/user.css
  user/user.html
  user/user.js
  user/webfonts/fa-brands-400.ttf
  user/webfonts/fa-brands-400.woff2
  user/webfonts/fa-regular-400.ttf
  user/webfonts/fa-regular-400.woff2
  user/webfonts/fa-solid-900.ttf
  user/webfonts/fa-solid-900.woff2
  user/webfonts/fa-v4compatibility.ttf
  user/webfonts/fa-v4compatibility.woff2
Labels: waiting-reviwe
